#!/usr/bin/with-contenv bash

# Handle GALDIR_LISTEN GALDIR_SITENAME GALDIR_ALBUMS GALDIR_CACHE GALDIR_ITEMS_PERPAGE env variables
cat /usr/local/share/galdir/config.ini \
    | sed -E "s/(listen = ).*/\1${GALDIR_LISTEN}/" \
    | sed -E "s/(galdir.sitename = ).*/\1${GALDIR_SITENAME}/" \
    | sed -E "s/(galdir.dir_albums = ).*/\1${GALDIR_ALBUMS}/" \
    | sed -E "s/(galdir.dir_cache = ).*/\1${GALDIR_CACHE}/" \
    | sed -E "s/(galdir.items_perpage = ).*/\1${GALDIR_ITEMS_PERPAGE}/" \
    > /usr/local/share/galdir/production.ini