#!/usr/bin/with-contenv bash

config_file=/usr/local/share/galdir/galdir/config.py

# Initial config.py setup
echo "DEBUG=False" > $config_file
echo "SECRET_KEY=$(python3 -c 'import os; print(os.urandom(16))')" >> $config_file

# Handle all GALDIR_* environment variables
for var in ${!GALDIR_*} ; do
    echo $var=\""${!var}"\" >> $config_file
done
